// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: didi_protocol_psnger/didi_protocol_pushsvr.proto
package com.mots.protocol;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REQUIRED;

/**
 * 下发订单状态信息
 */
public final class PassengerOrderStatusReq extends Message {

    public static final Integer DEFAULT_STATUS = 0;
    public static final String DEFAULT_OID = "";
    public static final Integer DEFAULT_DRIVER_NUM = 0;
    public static final Integer DEFAULT_TIME_OUT = 0;
    public static final Integer DEFAULT_IS_ARRIVED = 0;
    public static final Integer DEFAULT_CONSULT_STATUS = 0;
    public static final Integer DEFAULT_SUB_STATUS = 0;
    public static final Integer DEFAULT_STRIVE_ORDER_DRIVER_NUM = 0;
    public static final Integer DEFAULT_COUNT_DOWN_TIME = 0;
    public static final String DEFAULT_PUSH_PASSENGER_MSG = "";
    public static final String DEFAULT_GET_LINE_MSG = "";

    @ProtoField(tag = 1, type = INT32, label = REQUIRED)
    public final Integer status;

    @ProtoField(tag = 2, type = STRING, label = REQUIRED)
    public final String oid;

    @ProtoField(tag = 3, type = INT32)
    public final Integer driver_num;

    @ProtoField(tag = 4)
    public final DriverInfo driver_info;

    @ProtoField(tag = 5)
    public final DriverPos driver_pos;

    @ProtoField(tag = 6, type = INT32, label = REQUIRED)
    public final Integer time_out;

    @ProtoField(tag = 7, type = INT32)
    public final Integer is_arrived;

    /**
     * 协商状态 0等待协商 1协商通过
     */
    @ProtoField(tag = 8, type = INT32)
    public final Integer consult_status;

    @ProtoField(tag = 9)
    public final ConsultInfo consult_info;

    /**
     * 子状态
     */
    @ProtoField(tag = 10, type = INT32)
    public final Integer sub_status;

    /**
     * 抢单司机数
     */
    @ProtoField(tag = 11, type = INT32)
    public final Integer strive_order_driver_num;

    /**
     * 倒计时秒数
     */
    @ProtoField(tag = 12, type = INT32)
    public final Integer count_down_time;

    /**
     * 给乘客下发的消息内容
     */
    @ProtoField(tag = 13, type = STRING)
    public final String push_passenger_msg;

    /**
     * 获取路线消息
     */
    @ProtoField(tag = 14, type = STRING)
    public final String get_line_msg;

    public PassengerOrderStatusReq(Integer status, String oid, Integer driver_num, DriverInfo driver_info, DriverPos driver_pos, Integer time_out, Integer is_arrived, Integer consult_status, ConsultInfo consult_info, Integer sub_status, Integer strive_order_driver_num, Integer count_down_time, String push_passenger_msg, String get_line_msg) {
        this.status = status;
        this.oid = oid;
        this.driver_num = driver_num;
        this.driver_info = driver_info;
        this.driver_pos = driver_pos;
        this.time_out = time_out;
        this.is_arrived = is_arrived;
        this.consult_status = consult_status;
        this.consult_info = consult_info;
        this.sub_status = sub_status;
        this.strive_order_driver_num = strive_order_driver_num;
        this.count_down_time = count_down_time;
        this.push_passenger_msg = push_passenger_msg;
        this.get_line_msg = get_line_msg;
    }

    private PassengerOrderStatusReq(Builder builder) {
        this(builder.status, builder.oid, builder.driver_num, builder.driver_info, builder.driver_pos, builder.time_out, builder.is_arrived, builder.consult_status, builder.consult_info, builder.sub_status, builder.strive_order_driver_num, builder.count_down_time, builder.push_passenger_msg, builder.get_line_msg);
        setBuilder(builder);
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof PassengerOrderStatusReq)) return false;
        PassengerOrderStatusReq o = (PassengerOrderStatusReq) other;
        return equals(status, o.status)
                && equals(oid, o.oid)
                && equals(driver_num, o.driver_num)
                && equals(driver_info, o.driver_info)
                && equals(driver_pos, o.driver_pos)
                && equals(time_out, o.time_out)
                && equals(is_arrived, o.is_arrived)
                && equals(consult_status, o.consult_status)
                && equals(consult_info, o.consult_info)
                && equals(sub_status, o.sub_status)
                && equals(strive_order_driver_num, o.strive_order_driver_num)
                && equals(count_down_time, o.count_down_time)
                && equals(push_passenger_msg, o.push_passenger_msg)
                && equals(get_line_msg, o.get_line_msg);
    }

    @Override
    public int hashCode() {
        int result = hashCode;
        if (result == 0) {
            result = status != null ? status.hashCode() : 0;
            result = result * 37 + (oid != null ? oid.hashCode() : 0);
            result = result * 37 + (driver_num != null ? driver_num.hashCode() : 0);
            result = result * 37 + (driver_info != null ? driver_info.hashCode() : 0);
            result = result * 37 + (driver_pos != null ? driver_pos.hashCode() : 0);
            result = result * 37 + (time_out != null ? time_out.hashCode() : 0);
            result = result * 37 + (is_arrived != null ? is_arrived.hashCode() : 0);
            result = result * 37 + (consult_status != null ? consult_status.hashCode() : 0);
            result = result * 37 + (consult_info != null ? consult_info.hashCode() : 0);
            result = result * 37 + (sub_status != null ? sub_status.hashCode() : 0);
            result = result * 37 + (strive_order_driver_num != null ? strive_order_driver_num.hashCode() : 0);
            result = result * 37 + (count_down_time != null ? count_down_time.hashCode() : 0);
            result = result * 37 + (push_passenger_msg != null ? push_passenger_msg.hashCode() : 0);
            result = result * 37 + (get_line_msg != null ? get_line_msg.hashCode() : 0);
            hashCode = result;
        }
        return result;
    }

    public static final class Builder extends Message.Builder<PassengerOrderStatusReq> {

        public Integer status;
        public String oid;
        public Integer driver_num;
        public DriverInfo driver_info;
        public DriverPos driver_pos;
        public Integer time_out;
        public Integer is_arrived;
        public Integer consult_status;
        public ConsultInfo consult_info;
        public Integer sub_status;
        public Integer strive_order_driver_num;
        public Integer count_down_time;
        public String push_passenger_msg;
        public String get_line_msg;

        public Builder() {
        }

        public Builder(PassengerOrderStatusReq message) {
            super(message);
            if (message == null) return;
            this.status = message.status;
            this.oid = message.oid;
            this.driver_num = message.driver_num;
            this.driver_info = message.driver_info;
            this.driver_pos = message.driver_pos;
            this.time_out = message.time_out;
            this.is_arrived = message.is_arrived;
            this.consult_status = message.consult_status;
            this.consult_info = message.consult_info;
            this.sub_status = message.sub_status;
            this.strive_order_driver_num = message.strive_order_driver_num;
            this.count_down_time = message.count_down_time;
            this.push_passenger_msg = message.push_passenger_msg;
            this.get_line_msg = message.get_line_msg;
        }

        public Builder status(Integer status) {
            this.status = status;
            return this;
        }

        public Builder oid(String oid) {
            this.oid = oid;
            return this;
        }

        public Builder driver_num(Integer driver_num) {
            this.driver_num = driver_num;
            return this;
        }

        public Builder driver_info(DriverInfo driver_info) {
            this.driver_info = driver_info;
            return this;
        }

        public Builder driver_pos(DriverPos driver_pos) {
            this.driver_pos = driver_pos;
            return this;
        }

        public Builder time_out(Integer time_out) {
            this.time_out = time_out;
            return this;
        }

        public Builder is_arrived(Integer is_arrived) {
            this.is_arrived = is_arrived;
            return this;
        }

        /**
         * 协商状态 0等待协商 1协商通过
         */
        public Builder consult_status(Integer consult_status) {
            this.consult_status = consult_status;
            return this;
        }

        public Builder consult_info(ConsultInfo consult_info) {
            this.consult_info = consult_info;
            return this;
        }

        /**
         * 子状态
         */
        public Builder sub_status(Integer sub_status) {
            this.sub_status = sub_status;
            return this;
        }

        /**
         * 抢单司机数
         */
        public Builder strive_order_driver_num(Integer strive_order_driver_num) {
            this.strive_order_driver_num = strive_order_driver_num;
            return this;
        }

        /**
         * 倒计时秒数
         */
        public Builder count_down_time(Integer count_down_time) {
            this.count_down_time = count_down_time;
            return this;
        }

        /**
         * 给乘客下发的消息内容
         */
        public Builder push_passenger_msg(String push_passenger_msg) {
            this.push_passenger_msg = push_passenger_msg;
            return this;
        }

        /**
         * 获取路线消息
         */
        public Builder get_line_msg(String get_line_msg) {
            this.get_line_msg = get_line_msg;
            return this;
        }

        @Override
        public PassengerOrderStatusReq build() {
            checkRequiredFields();
            return new PassengerOrderStatusReq(this);
        }
    }
}
